# Generated by Django 4.1.3 on 2022-12-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("sub", models.TextField(null=True)),
                ("side", models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("subtitle", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "large_price",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "quart_price",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "bottle_price",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("menu_number", models.CharField(max_length=6, null=True)),
                (
                    "lunch",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=4,
                    ),
                ),
                (
                    "dinner",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=4,
                    ),
                ),
                (
                    "substitute",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=4,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Large", "Large"),
                            ("Pint", "Pint"),
                            ("Quart", "Quart"),
                            ("Can", "Can"),
                            ("20 oz.", "Bottle"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "spicy",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=4, null=True
                    ),
                ),
                (
                    "header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="china_ocean.header",
                    ),
                ),
            ],
        ),
    ]
