# Generated by Django 4.1.3 on 2022-12-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("china_ocean", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item", name="subtitle", field=models.TextField(null=True),
        ),
    ]
