# Generated by Django 4.1.3 on 2022-12-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("china_ocean", "0002_alter_item_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="bottle_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="large_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="menu_number",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="quart_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Small", "Small"),
                    ("Large", "Large"),
                    ("Pint", "Pint"),
                    ("Quart", "Quart"),
                    ("Can", "Can"),
                    ("20 oz.", "Bottle"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="spicy",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=4,
                null=True,
            ),
        ),
    ]
