# Generated by Django 4.1.3 on 2022-12-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("china_ocean", "0003_alter_item_bottle_price_alter_item_large_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="header",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
