# Generated by Django 4.1.3 on 2022-12-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("china_ocean", "0004_header_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="substitute",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=4,
                null=True,
            ),
        ),
    ]
