# Generated by Django 4.1.3 on 2022-12-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("china_ocean", "0006_alter_item_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="dinner_number",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="lunch_number",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
