# Generated by Django 4.1.3 on 2022-12-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("china_ocean", "0007_item_dinner_number_item_lunch_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="combo_lunch_number",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="number",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=6, null=True
            ),
        ),
    ]
