# Generated by Django 4.1.3 on 2023-05-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("china_ocean", "0009_item_dinner_image_item_image_item_lunch_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="dinner_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="dishes/dinner-special/"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="dishes/"),
        ),
        migrations.AlterField(
            model_name="item",
            name="lunch_image",
            field=models.ImageField(blank=True, null=True, upload_to="dishes/lunch/"),
        ),
    ]
