# Generated by Django 4.1.3 on 2023-05-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("china_ocean", "0010_alter_item_dinner_image_alter_item_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="dinner_image",),
        migrations.RemoveField(model_name="item", name="image",),
        migrations.RemoveField(model_name="item", name="lunch_image",),
        migrations.AddField(
            model_name="item",
            name="dinner_image_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="lunch_image_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
